user: root
enable_ssh_minions: True
userdata_template: jinja
ssh_user: ec2-user
file_recv: True
fileserver_followsymlinks: True
state_top: top.sls


gitfs_provider: gitpython  # pygit2 is the recommended provider
git_pillar_provider: gitpython  # Ensure the same provider is used for pillars

fileserver_backend:
  - gitfs

gitfs_remotes:
  - ssh://git@github.com/ohuweih/salt_configuration.git:
    - base: main
    - mountpoint: salt://
  - ssh://git@github.com/ohuweih/salt_provision.git:
    - base: main
    - mountpoint: salt://

ssh_known_hosts_file: /root/.ssh/known_hosts

gitfs_global_lock: False

# Pillar backend configuration
pillar_opts: True

ext_pillar:
  - git:
    - main https://github.com/ohuweih/salt_pillar.git:
      - env: base
      - root: /
